# Generated by Django 5.0.1 on 2024-01-11 14:17

import django.db.models.deletion
import operations.models.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('minus', 'Minus'), ('plus', 'Plus')], max_length=15)),
                ('amount', models.CharField(max_length=256, validators=[operations.models.operations.amount_validators])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='OperationsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('new_balance', models.CharField(max_length=256)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.operation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.balanceruser')),
            ],
        ),
    ]
